# Generated by Django 4.2 on 2023-11-02 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("introduction_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="skill",
            name="image",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
